# These are supported funding model platforms

github: svglan
==== codex/replace-repository-links-with-mine-pwb4d6 ====
ko_fi: svglan
buy_me_a_coffee: svglan
=========================================================
ko_fi: jakoolit

